driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7


suites:
  #- name: default
  #  run_list: wra_activemq::legacy
  - name: resource_based
    run_list: wra_activemq::default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
